### ISSUE TITLE
FC Settings

### ISSUE THREAD

**Issue by lehoangnb** [MoKee/android_packages_apps_Settings#26]
E/AndroidRuntime( 2506): FATAL EXCEPTION: main
E/AndroidRuntime( 2506): Process: com.android.settings, PID: 2506
E/AndroidRuntime( 2506): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/priv-app/Settings/Settings.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libjpush174.so"
E/AndroidRuntime( 2506):    at java.lang.Runtime.loadLibrary(Runtime.java:366)
E/AndroidRuntime( 2506):    at java.lang.System.loadLibrary(System.java:988)
E/AndroidRuntime( 2506):    at cn.jpush.android.service.PushProtocol.<clinit>(Unknown Source)
E/AndroidRuntime( 2506):    at cn.jpush.android.service.ServiceInterface.a(Unknown Source)
E/AndroidRuntime( 2506):    at cn.jpush.android.api.JPushInterface.init(Unknown Source)
E/AndroidRuntime( 2506):    at com.mokee.helper.MoKeeApplication.onCreate(MoKeeApplication.java:89)
E/AndroidRuntime( 2506):    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
E/AndroidRuntime( 2506):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588)
E/AndroidRuntime( 2506):    at android.app.ActivityThread.access$1600(ActivityThread.java:154)
E/AndroidRuntime( 2506):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
E/AndroidRuntime( 2506):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 2506):    at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 2506):    at android.app.ActivityThread.main(ActivityThread.java:5289)
E/AndroidRuntime( 2506):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2506):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 2506):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime( 2506):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by martincz** [comment]
Can you tell me what's your device name and version code?

**Comment by lehoangnb** [comment]
My device is Sky IM-A870 (ef52l), mkl-mr1. After I sync new mokee source, build ok, but Settings is force close.

**Comment by martincz** [comment]
Have you remove any files in vendor/mk?

**Comment by lehoangnb** [comment]
No, I did not!

**Comment by lehoangnb** [comment]
This error file "/system/priv-app/Settings/Settings.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libjpush174.so"
libjpush174.so not found in system/lib, but in old build, I found that file in system/lib

**Comment by martincz** [comment]
try compile a image?

---

Best Regards
Martincz.Gao

Email:martincz@mokeedev.com
Weibo:http://weibo.com/martincz

MoKee OpenSource Team
Illustrating Your Mobile Life.

原始邮件
发件人:Le Viet Hoangnotifications@github.com
收件人:MoKee/android_packages_apps_Settingsandroid_packages_apps_Settings@noreply.github.com
抄送:martinczmartincz@mokeedev.com
发送时间:2015年6月27日(周六) 22:04
主题:Re: [android_packages_apps_Settings] FC Settings (#26)

This error file "/system/priv-app/Settings/Settings.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libjpush174.so"
 libjpush174.so not found in system/lib, but in old build, I found that file in system/lib

**Comment by lehoangnb** [comment]
What you say? I dont understand.

**Comment by jarvanh** [comment]
@CryToCry96 @martincz 

I also have this problem.

Each boot will like this.

![](http://i.imgur.com/YcfgGA4.png)

![](http://i.imgur.com/GLiqYYH.png)

![](http://i.imgur.com/ntFj1cl.png)
